# Generated by Django 3.0.4 on 2020-04-02 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_add_iso_code_to_honduras'),
        ('company', '0104_company_dnb_investigation_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyExportOverseasRegion',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_interested', 'Not interested'), ('currently_exporting', 'Currently exporting to'), ('future_interest', 'Future country of interest')], max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_regions', to='company.Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies_with_interest', to='metadata.OverseasRegion')),
            ],
            options={
                'verbose_name_plural': 'company export region',
            },
        ),
        migrations.AddConstraint(
            model_name='companyexportoverseasregion',
            constraint=models.UniqueConstraint(fields=('region', 'company'), name='unique_region_company'),
        ),
    ]
