# This workflow verifies that news fragments are named correctly.

name: Check names of news fragments

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop

jobs:
  check_news_fragment:
    name: Check news fragments
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      
      - name: Install towncrier
        run: |
          python -m pip install towncrier
      
      - name: Generate list of news fragments
        run: echo |
          python scripts/script_utils/news_fragments.py
